name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security tests
      run: |
        npm run test:security
        npm audit --audit-level moderate
        node scripts/check-permissions.js
        
    - name: Auto-merge patch updates
      if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
      run: |
        gh pr review --approve "$PR_URL"
        gh pr merge --auto --merge "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Auto-approve minor updates (manual merge required)
      if: steps.metadata.outputs.update-type == 'version-update:semver-minor'
      run: |
        gh pr review --approve "$PR_URL"
        gh pr comment "$PR_URL" --body "✅ Auto-approved minor dependency update. Please review and merge manually after CI passes."
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Comment on major updates
      if: steps.metadata.outputs.update-type == 'version-update:semver-major'
      run: |
        gh pr comment "$PR_URL" --body "⚠️ Major dependency update detected. Please review carefully for breaking changes before merging."
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}